# hello_page:
#   path: /
#   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#   defaults: 
#     template: 'hello_page.html.twig'

index:
  path: /
  controller: App\Controller\HomeController:index